---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.15.1
    app.quarkus.io/vcs-uri: https://github.com/edgarssilva/quarkus-ecommerce.git
  labels:
    app.kubernetes.io/name: altice-ecommerce
    app.kubernetes.io/managed-by: quarkus
  name: altice-ecommerce
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: altice-ecommerce
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.15.1
    app.quarkus.io/vcs-uri: https://github.com/edgarssilva/quarkus-ecommerce.git
  labels:
    app.kubernetes.io/name: altice-ecommerce
    app.kubernetes.io/managed-by: quarkus
  name: altice-ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: altice-ecommerce
  template:
    metadata:
      annotations:
        app.quarkus.io/quarkus-version: 3.15.1
        app.quarkus.io/vcs-uri: https://github.com/edgarssilva/quarkus-ecommerce.git
      labels:
        app.kubernetes.io/managed-by: quarkus
        app.kubernetes.io/name: altice-ecommerce
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: docker.io/edgar/altice-ecommerce:1.0-SNAPSHOT
          imagePullPolicy: Always
          name: altice-ecommerce
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
